app:
  message: message succesfuly sent
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange
    routingkey: user.routingkey
server:
  port: 8081
